### ISSUE TITLE
Output.txt doesn't contain anything.

### ISSUE THREAD

**Issue by ChiragSoni95** [laxmanverma/Scripts#1]
What exactly do you store in the output.txt apart from the pdf links, because it successfully runs but nothing is wrote in output.txt (after uncommenting the lines too).

**Comment by laxmanverma** [comment]
which python version are you using?
Use 2.7

**Comment by ChiragSoni95** [comment]
@laxmanverma , I am using python 3.6.
I tried to uncomment line number, 46-48 and 65-68, it just shows the hyperlink I entered and then it just runs and doesn't stop running.
I get the following output:
<img width="1069" alt="screen shot 2018-07-15 at 7 06 44 pm" src="https://user-images.githubusercontent.com/32116674/42740933-4e178072-8862-11e8-9617-3588412ec725.png">

**Comment by ChiragSoni95** [comment]
@laxmanverma Okay I will try with python 2.7 and let you know.
Thanks

**Comment by ChiragSoni95** [comment]
I tried running it on 2.7
It gives this error, and I tried printing pdfName and pdflink, it gives the following output:

Error Stack Trace:
Traceback (most recent call last):
  File "/Users/chirag/PycharmProjects/LayoutLearning/scrape_pdfs.py", line 83, in <module>
    lookUp ();
  File "/Users/chirag/PycharmProjects/LayoutLearning/scrape_pdfs.py", line 80, in lookUp
    crawlPage ( htmlSourceCode )
  File "/Users/chirag/PycharmProjects/LayoutLearning/scrape_pdfs.py", line 66, in crawlPage
    urllib.urlretrieve ( pdfLink, pdfName )
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 469, in open_file
    return self.open_local_file(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 483, in open_local_file
    raise IOError(e.errno, e.strerror, e.filename)
IOError: [Errno 2] No such file or directory: ''

Print output:
physics-All The Best For You Board Exams-TYPE html>
<html lang="en">
<head lang="en">
<meta charset="UTF-8" />
<meta name="viewport" content="initial-scale=1.0" />
<title>CBSE 12th Science Previous Year Question Papers All Subjects</title>
<link rel="profile" href="http://gmpg.org/xfn/11" />
<link rel="pingback" href="http://www.4ono.com/xmlrpc.php" />


<meta name="description"  content="Download CBSE 12th Science Previous Year Question Papers All Subjects PDF, www.samplepapercbse.com, All India(AI) and Delhi Board. Previous 5 to 10 years" />

<meta name="keywords"  content="cbse 12th previous year papers,12th last 10 year papers,12th previous 10 year papers solution,cbse,sample papers" />

<link rel="canonical" href="http://www.4ono.com/cbse-12th-science-previous-year-question-papers-pdf-201617/" />
<meta property="og:title" content="CBSE 12th Science Previous Year Question Papers All Subjects" />
<meta property="og:type" content="activity" />
<meta property="og:url" content="http://www.4ono.com/cbse-12th-science-previous-year-question-papers-pdf-201617/" />
<meta property="og:image" content="http://www.4ono.com/wp-content/uploads/2015/12/CBSE-12th-Science-Previous-Year-Question-Papers-1024x640.jpg" />
<meta property="og:site_name" content="4ONO" />
<meta property="fb:admins" content="167581003304812" />
<meta property="og:description" content="Download CBSE 12th Science Previous Year Question Papers All Subjects PDF, www.samplepapercbse.com, All India(AI) and Delhi Board. Previous 5 to 10 years Practice papers 2018" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@TeamSqeets" />
<meta name="twitter:domain" content="4ono" />
<meta name="twitter:title" content="CBSE 12th Science Previous Year Question Papers All Subjects" />
<meta name="twitter:description" content="Download CBSE 12th Science Previous Year Question Papers All Subjects PDF, www.samplepapercbse.com, All India(AI) and Delhi Board. Previous 5 to 10 years Practice papers 2018" />
<meta name="twitter:image" content="http://www.4ono.com/wp-content/uploads/2015/12/CBSE-12th-Science-Previous-Year-Question-Papers-1024x640.jpg" />
<meta itemprop="image" content="http://www.4ono.com/wp-content/uploads/2015/12/CBSE-12th-Science-Previous-Year-Question-Papers-1024x640.jpg" />

<link rel='dns-prefetch' href='//s.w.org' />
<link rel="alternate" type="application/rss+xml" title="4ONO &raquo; Feed" href="http://www.4ono.com/feed/" />
<link rel="alternate" type="application/rss+xml" title="4ONO &raquo; Comments Feed" href="http://www.4ono.com/comments/feed/" />
<link rel="alternate" type="application/rss+xml" title="4ONO &raquo; Download CBSE 12th Science Previous Year Question Papers All Subjects PDF Comments Feed" href="http://www.4ono.com/cbse-12th-science-previous-year-question-papers-pdf-201617/feed/" />
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://www.4ono.com/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://www.4ono.com/wp-includes/wlwmanifest.xml" /> 
<link rel='prev' title='CBSE 12th Hindi Core &#038; Elective Previous Years Question Papers PDF' href='http://www.4ono.com/cbse-class-12th-hindi-core-elective-previous-years-papers-20152016/' />
<link rel='next' title='Download Political Science CBSE 12th Previous 5-10 Years Question Papers PDF' href='http://www.4ono.com/political-science-cbse-12th-question-papers-20152016/' />
<meta name="generator" content="WordPress 4.8.2" />
<link rel='shortlink' href='http://www.4ono.com/?p=722' />
<link rel="alternate" type="application/json+oembed" href="http://www.4ono.com/wp-json/oembed/1.0/embed?url=http%3A%2F%2Fwww.4ono.com%2Fcbse-12th-science-previous-year-question-papers-pdf-201617%2F" />
<link rel="icon" href="http://www.4ono.com/wp-content/uploads/2017/09/favico.png" type="image/x-icon">
<link rel="stylesheet" href="http://www.4ono.com/wp-content/themes/ono/style.css?1.6.10" type="text/css" media="all">
</head>
<body>
<div class="header">
    <div>
        <div class="box top_ono">
            <a class="logo" href="http://www.4ono.com/" title="Jobs, Recruitment, Result, Answer Key, Admit Card, News">
                <img aria-label="4ono Home" src="http://www.4ono.com/wp-content/themes/ono/static/img/logo.png"
                     alt="Jobs, Recruitment, Result, Answer Key, Admit Card, News" height="29">
            .pdf

**Comment by laxmanverma** [comment]
Ok I'll check and let you know.
It may be possible that the html Dom of this site is changed.

**Comment by ChiragSoni95** [comment]
Yes.
so what can I do to make this generic, every site will be having a separate DOM structure, I want to retrieve as many pdfs from web as much as I can.
What can I do for that?
Can you help?

**Comment by laxmanverma** [comment]
If you want to download only PDF files then search href ending with .pdf in
Dom of any site.
I'll make it generic by next weekend.

**Comment by ChiragSoni95** [comment]
Okay thanks!!
I will try!
